// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// FWERkControl
List FWERkControl(arma::vec test_stat, arma::mat boot_stat, int k, double alpha);
RcppExport SEXP StepwiseTest_FWERkControl(SEXP test_statSEXP, SEXP boot_statSEXP, SEXP kSEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::vec >::type test_stat(test_statSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type boot_stat(boot_statSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    __result = Rcpp::wrap(FWERkControl(test_stat, boot_stat, k, alpha));
    return __result;
END_RCPP
}
// FDPControl
List FDPControl(arma::vec test_stat, arma::mat boot_stat, double gamma, double alpha);
RcppExport SEXP StepwiseTest_FDPControl(SEXP test_statSEXP, SEXP boot_statSEXP, SEXP gammaSEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::vec >::type test_stat(test_statSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type boot_stat(boot_statSEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    __result = Rcpp::wrap(FDPControl(test_stat, boot_stat, gamma, alpha));
    return __result;
END_RCPP
}
