# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

FWERkControl <- function(test_stat, boot_stat, k, alpha) {
    .Call('StepwiseTest_FWERkControl', PACKAGE = 'StepwiseTest', test_stat, boot_stat, k, alpha)
}

FDPControl <- function(test_stat, boot_stat, gamma, alpha) {
    .Call('StepwiseTest_FDPControl', PACKAGE = 'StepwiseTest', test_stat, boot_stat, gamma, alpha)
}

